// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	kcp "github.com/platform-mesh/kubernetes-graphql-gateway/listener/reconciler/kcp"
	mock "github.com/stretchr/testify/mock"
)

// MockVirtualWorkspaceConfigReconciler is an autogenerated mock type for the VirtualWorkspaceConfigReconciler type
type MockVirtualWorkspaceConfigReconciler struct {
	mock.Mock
}

type MockVirtualWorkspaceConfigReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVirtualWorkspaceConfigReconciler) EXPECT() *MockVirtualWorkspaceConfigReconciler_Expecter {
	return &MockVirtualWorkspaceConfigReconciler_Expecter{mock: &_m.Mock}
}

// ReconcileConfig provides a mock function with given fields: ctx, config
func (_m *MockVirtualWorkspaceConfigReconciler) ReconcileConfig(ctx context.Context, config *kcp.VirtualWorkspacesConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kcp.VirtualWorkspacesConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileConfig'
type MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call struct {
	*mock.Call
}

// ReconcileConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config *kcp.VirtualWorkspacesConfig
func (_e *MockVirtualWorkspaceConfigReconciler_Expecter) ReconcileConfig(ctx interface{}, config interface{}) *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call {
	return &MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call{Call: _e.mock.On("ReconcileConfig", ctx, config)}
}

func (_c *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call) Run(run func(ctx context.Context, config *kcp.VirtualWorkspacesConfig)) *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kcp.VirtualWorkspacesConfig))
	})
	return _c
}

func (_c *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call) Return(_a0 error) *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call) RunAndReturn(run func(context.Context, *kcp.VirtualWorkspacesConfig) error) *MockVirtualWorkspaceConfigReconciler_ReconcileConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVirtualWorkspaceConfigReconciler creates a new instance of MockVirtualWorkspaceConfigReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVirtualWorkspaceConfigReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVirtualWorkspaceConfigReconciler {
	mock := &MockVirtualWorkspaceConfigReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
