// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	kcp "github.com/platform-mesh/kubernetes-graphql-gateway/listener/reconciler/kcp"
	mock "github.com/stretchr/testify/mock"
)

// MockVirtualWorkspaceConfigManager is an autogenerated mock type for the VirtualWorkspaceConfigManager type
type MockVirtualWorkspaceConfigManager struct {
	mock.Mock
}

type MockVirtualWorkspaceConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVirtualWorkspaceConfigManager) EXPECT() *MockVirtualWorkspaceConfigManager_Expecter {
	return &MockVirtualWorkspaceConfigManager_Expecter{mock: &_m.Mock}
}

// LoadConfig provides a mock function with given fields: configPath
func (_m *MockVirtualWorkspaceConfigManager) LoadConfig(configPath string) (*kcp.VirtualWorkspacesConfig, error) {
	ret := _m.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *kcp.VirtualWorkspacesConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*kcp.VirtualWorkspacesConfig, error)); ok {
		return rf(configPath)
	}
	if rf, ok := ret.Get(0).(func(string) *kcp.VirtualWorkspacesConfig); ok {
		r0 = rf(configPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kcp.VirtualWorkspacesConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(configPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVirtualWorkspaceConfigManager_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockVirtualWorkspaceConfigManager_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - configPath string
func (_e *MockVirtualWorkspaceConfigManager_Expecter) LoadConfig(configPath interface{}) *MockVirtualWorkspaceConfigManager_LoadConfig_Call {
	return &MockVirtualWorkspaceConfigManager_LoadConfig_Call{Call: _e.mock.On("LoadConfig", configPath)}
}

func (_c *MockVirtualWorkspaceConfigManager_LoadConfig_Call) Run(run func(configPath string)) *MockVirtualWorkspaceConfigManager_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockVirtualWorkspaceConfigManager_LoadConfig_Call) Return(_a0 *kcp.VirtualWorkspacesConfig, _a1 error) *MockVirtualWorkspaceConfigManager_LoadConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVirtualWorkspaceConfigManager_LoadConfig_Call) RunAndReturn(run func(string) (*kcp.VirtualWorkspacesConfig, error)) *MockVirtualWorkspaceConfigManager_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVirtualWorkspaceConfigManager creates a new instance of MockVirtualWorkspaceConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVirtualWorkspaceConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVirtualWorkspaceConfigManager {
	mock := &MockVirtualWorkspaceConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
