version: "2"
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(k8s.io,sigs.k8s.io)
        - prefix(sigs.k8s.io/multicluster-runtime)
        - prefix(github.com/kcp-dev)
        - prefix(github.com/kcp-dev/multicluster-provider)
        - blank
        - dot
      custom-order: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - .*conversion.*\.go$
      - third_party$
      - builtin$
      - examples$

linters:
  exclusions:
    paths:
      - watcher_test\.go$
