issue-845-fix: true
resolve-type-alias: false
with-expecter: true
packages:
  k8s.io/client-go/discovery:
    config:
      dir: listener/reconciler/kcp/mocks
      outpkg: mocks
    interfaces:
      DiscoveryInterface:

  k8s.io/apimachinery/pkg/api/meta:
    config:
      dir: listener/reconciler/kcp/mocks
      outpkg: mocks
    interfaces:
      RESTMapper:

  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: common/mocks
      outpkg: mocks
    interfaces:
      WithWatch:
      Client:

  net/http:
    config:
      dir: gateway/manager/mocks
      outpkg: mocks
    interfaces:
      RoundTripper:

  github.com/platform-mesh/kubernetes-graphql-gateway/listener/pkg/workspacefile:
    config:
      dir: listener/pkg/workspacefile/mocks
      outpkg: mocks
    interfaces:
      IOHandler:

  github.com/platform-mesh/kubernetes-graphql-gateway/listener/reconciler/kcp/discoveryclient:
    config:
      dir: listener/reconciler/kcp/discoveryclient/mocks
      outpkg: mocks
    interfaces:
      Factory:

  github.com/platform-mesh/kubernetes-graphql-gateway/listener/pkg/apischema:
    config:
      dir: listener/pkg/apischema/mocks
      outpkg: mocks
    interfaces:
      Resolver:

  github.com/platform-mesh/kubernetes-graphql-gateway/listener/reconciler/kcp/clusterpath:
    config:
      dir: listener/reconciler/kcp/clusterpath/mocks
      outpkg: mocks
    interfaces:
      Resolver:

  k8s.io/client-go/openapi:
    config:
      dir: listener/pkg/apischema/mocks
      outpkg: mocks
    interfaces:
      GroupVersion:
      Client:

  github.com/platform-mesh/kubernetes-graphql-gateway/gateway/manager:
    config:
      dir: gateway/manager/mocks
      outpkg: mocks
    interfaces:
      ClusterManager:
      SchemaWatcher:
