exclude:
  paths:
    - main.go
    - cmd
    - tests
    - common/config/config.go
    - mocks
    - common/apis/*
    - export_test.go
    - export_test_integration.go
    # remove it later:
    - listener/reconciler/clusteraccess/subroutines.go

