version = 1
SPDX-PackageName = "kubernetes-graphql-gateway"
SPDX-PackageDownloadLocation = "https://github.com/platform-mesh/kubernetes-graphql-gateway"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and platform-mesh contributors and portal contributors."
SPDX-License-Identifier = "Apache-2.0"