version: '3'

dotenv: ['.taskenv', '.secret/.env', '{{.HOME}}/.env' ]
vars:
  LOCAL_BIN: bin
  ENVTEST_K8S_VERSION: "1.30.0" # to get latest version run $(pwd)/bin/setup-envtest list
  ENVTEST_VERSION: "release-0.20" # https://github.com/kubernetes-sigs/controller-runtime/releases
  MOCKERY_VERSION: v2.52.3 # https://github.com/vektra/mockery/releases
  CONTROLLER_GEN_VERSION: v0.18.0 # https://github.com/kubernetes-sigs/controller-tools/releases
  GOLANGCI_LINT_VERSION: v2.6.0
  KCP_APIGEN_VERSION: v0.29.0 # https://pkg.go.dev/github.com/kcp-dev/sdk
tasks:
  ## Setup
  setup:mockery:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/mockery || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
  setup:envtest:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/setup-envtest || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install sigs.k8s.io/controller-runtime/tools/setup-envtest@{{.ENVTEST_VERSION}}
  setup:controller-gen:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/controller-gen || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install sigs.k8s.io/controller-tools/cmd/controller-gen@{{.CONTROLLER_GEN_VERSION}}
  setup:golangci-lint:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/golangci-lint || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
  setup:go-test-coverage:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/go-test-coverage || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/vladopajic/go-test-coverage/v2@latest
  setup:kcp-apigen:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/apigen || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/kcp-dev/sdk/cmd/apigen@{{.KCP_APIGEN_VERSION}}

  ## Code Generation
  generate:
    desc: "Generate all CRD-related files (manifests + deepcopy methods)"
    deps: [setup:controller-gen, setup:kcp-apigen ]
    cmds:
      - "{{.LOCAL_BIN}}/controller-gen object crd:crdVersions=v1 paths=./common/apis/v1alpha1 output:crd:artifacts:config=config/crd"
      - "{{.LOCAL_BIN}}/apigen --output-dir config/kcp --input-dir config/crd"

  ## Development
  mockery:
    deps: [ setup:mockery ]
    cmds:
      - "{{.LOCAL_BIN}}/mockery"
  docker:
    cmds:
      - docker build -t ghcr.io/platform-mesh/kubernetes-graphql-gateway .

  docker:kind:
    desc: "Build container image with current tag from kind cluster and load it"
    vars:
      CONTAINER_RUNTIME: '{{.CONTAINER_RUNTIME | default "docker"}}'
      KIND_CLUSTER: '{{.KIND_CLUSTER | default "platform-mesh"}}'
      DEPLOYMENT_NAME: '{{.DEPLOYMENT_NAME | default "kubernetes-graphql-gateway"}}'
      DEPLOYMENT_NAMESPACE: '{{.DEPLOYMENT_NAMESPACE | default "platform-mesh-system"}}'
      IMAGE_TAG:
        sh: kubectl get deployment {{.DEPLOYMENT_NAME}} -n {{.DEPLOYMENT_NAMESPACE}} -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2
      IMAGE_NAME: ghcr.io/platform-mesh/kubernetes-graphql-gateway:{{.IMAGE_TAG}}
    cmds:
      - echo "Building image with tag {{.IMAGE_TAG}} using {{.CONTAINER_RUNTIME}}"
      - "{{.CONTAINER_RUNTIME}} build -t {{.IMAGE_NAME}} ."
      - |
        if [ "{{.CONTAINER_RUNTIME}}" = "podman" ]; then
          {{.CONTAINER_RUNTIME}} save {{.IMAGE_NAME}} -o /tmp/kind-image.tar
          kind load image-archive /tmp/kind-image.tar --name {{.KIND_CLUSTER}}
          rm -f /tmp/kind-image.tar
        else
          kind load docker-image {{.IMAGE_NAME}} --name {{.KIND_CLUSTER}}
        fi
      - kubectl rollout restart deployment/{{.DEPLOYMENT_NAME}} -n {{.DEPLOYMENT_NAMESPACE}}
      - echo "Image loaded and deployment restarted"
  ## Testing
  fmt:
    cmds:
      - "{{.LOCAL_BIN}}/golangci-lint fmt ./..."
  lint:
    deps: [setup:golangci-lint]
    cmds:
      - task: fmt
      - "{{.LOCAL_BIN}}/golangci-lint run --timeout 10m ./..."
  envtest:
    deps: [setup:envtest]
    env:
      KUBEBUILDER_ASSETS:
        # Workaround for setup-envtest bug: it doesn't verify binaries exist if directory is present
        sh: |
          ASSETS_PATH=$(pwd)/{{.LOCAL_BIN}}/k8s/{{.ENVTEST_K8S_VERSION}}-$(go env GOOS)-$(go env GOARCH)
          if [ ! -x "$ASSETS_PATH/etcd" ] || [ ! -x "$ASSETS_PATH/kube-apiserver" ]; then
            $(pwd)/{{.LOCAL_BIN}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir $(pwd)/{{.LOCAL_BIN}} --force -p path
          else
            echo "$ASSETS_PATH"
          fi
    cmds:
      - go test ./... {{.ADDITIONAL_COMMAND_ARGS}}
  test:
    deps: [setup:envtest]
    cmds:
      - task: envtest
        vars:
          ADDITIONAL_COMMAND_ARGS: -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
  cover:
    deps: [setup:envtest, setup:go-test-coverage ]
    cmds:
      - task: envtest
        vars:
          ADDITIONAL_COMMAND_ARGS: -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - "{{.LOCAL_BIN}}/go-test-coverage --profile cover.out --config ./.testcoverage.yml"
  cover-html:
    desc: "Generate and open HTML coverage report"
    deps: [cover]
    cmds:
      - go tool cover -html=cover.out -o coverage.html
      - open coverage.html || xdg-open coverage.html || start coverage.html
  validate:
    desc: "Run all validation checks including code generation, linting, and testing"
    cmds:
      - task: generate
      - task: mockery
      - task: lint
      - task: test

  proto:
    desc: "Generate protobuf files"
    cmds:
      - protoc --go_out=. --go-grpc_out=. --go_opt=module=github.com/platform-mesh/kubernetes-graphql-gateway --go-grpc_opt=module=github.com/platform-mesh/kubernetes-graphql-gateway ./apis/proto/schemahandler.proto

  gateway:
    desc: "Start the GraphQL gateway server (kills existing process on port 8080 if needed)"
    cmds:
      - |
        # Check if port 8080 is in use and kill the process if found
        PID=$(lsof -ti:8080 2>/dev/null || echo "")
        if [ ! -z "$PID" ]; then
          echo "Found existing process $PID on port 8080, killing it..."
          kill $PID 2>/dev/null || true
          sleep 2
        fi
      - go run ./cmd/gateway/gateway.go --enable-playground

  listener:
    desc: "Start the listener server (kills existing process on port 8090 if needed)"
    cmds:
      - go run ./cmd/listener/listener.go 

  listener-kcp:
    desc: "Start the listener server (kills existing process on port 8090 if needed)"
    cmds:
      - go run ./cmd/listener/listener.go --apiexport-endpoint-slice-name gateway.platform-mesh.io --multicluster-runtime-provider kcp --kubeconfig=.secret/cc-d2-kcp.yaml
