// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: listener/pkg/schemahandler/proto/schemahandler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeResponse_EventType int32

const (
	SubscribeResponse_ADDED   SubscribeResponse_EventType = 0
	SubscribeResponse_REMOVED SubscribeResponse_EventType = 1
)

// Enum value maps for SubscribeResponse_EventType.
var (
	SubscribeResponse_EventType_name = map[int32]string{
		0: "ADDED",
		1: "REMOVED",
	}
	SubscribeResponse_EventType_value = map[string]int32{
		"ADDED":   0,
		"REMOVED": 1,
	}
)

func (x SubscribeResponse_EventType) Enum() *SubscribeResponse_EventType {
	p := new(SubscribeResponse_EventType)
	*p = x
	return p
}

func (x SubscribeResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_listener_pkg_schemahandler_proto_schemahandler_proto_enumTypes[0].Descriptor()
}

func (SubscribeResponse_EventType) Type() protoreflect.EnumType {
	return &file_listener_pkg_schemahandler_proto_schemahandler_proto_enumTypes[0]
}

func (x SubscribeResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeResponse_EventType.Descriptor instead.
func (SubscribeResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescGZIP(), []int{1, 0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescGZIP(), []int{0}
}

type SubscribeResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ClusterName   string                      `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Schema        string                      `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	EventType     SubscribeResponse_EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=proto.SubscribeResponse_EventType" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *SubscribeResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *SubscribeResponse) GetEventType() SubscribeResponse_EventType {
	if x != nil {
		return x.EventType
	}
	return SubscribeResponse_ADDED
}

var File_listener_pkg_schemahandler_proto_schemahandler_proto protoreflect.FileDescriptor

const file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDesc = "" +
	"\n" +
	"4listener/pkg/schemahandler/proto/schemahandler.proto\x12\x05proto\"\x12\n" +
	"\x10SubscribeRequest\"\xb6\x01\n" +
	"\x11SubscribeResponse\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12A\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\".proto.SubscribeResponse.EventTypeR\teventType\"#\n" +
	"\tEventType\x12\t\n" +
	"\x05ADDED\x10\x00\x12\v\n" +
	"\aREMOVED\x10\x012Q\n" +
	"\rSchemaHandler\x12@\n" +
	"\tSubscribe\x12\x17.proto.SubscribeRequest\x1a\x18.proto.SubscribeResponse0\x01BVZTgithub.com/platform-mesh/kubernetes-graphql-gateway/listener/pkg/schemahandler/protob\x06proto3"

var (
	file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescOnce sync.Once
	file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescData []byte
)

func file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescGZIP() []byte {
	file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescOnce.Do(func() {
		file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDesc), len(file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDesc)))
	})
	return file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDescData
}

var file_listener_pkg_schemahandler_proto_schemahandler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listener_pkg_schemahandler_proto_schemahandler_proto_goTypes = []any{
	(SubscribeResponse_EventType)(0), // 0: proto.SubscribeResponse.EventType
	(*SubscribeRequest)(nil),         // 1: proto.SubscribeRequest
	(*SubscribeResponse)(nil),        // 2: proto.SubscribeResponse
}
var file_listener_pkg_schemahandler_proto_schemahandler_proto_depIdxs = []int32{
	0, // 0: proto.SubscribeResponse.event_type:type_name -> proto.SubscribeResponse.EventType
	1, // 1: proto.SchemaHandler.Subscribe:input_type -> proto.SubscribeRequest
	2, // 2: proto.SchemaHandler.Subscribe:output_type -> proto.SubscribeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_listener_pkg_schemahandler_proto_schemahandler_proto_init() }
func file_listener_pkg_schemahandler_proto_schemahandler_proto_init() {
	if File_listener_pkg_schemahandler_proto_schemahandler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDesc), len(file_listener_pkg_schemahandler_proto_schemahandler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listener_pkg_schemahandler_proto_schemahandler_proto_goTypes,
		DependencyIndexes: file_listener_pkg_schemahandler_proto_schemahandler_proto_depIdxs,
		EnumInfos:         file_listener_pkg_schemahandler_proto_schemahandler_proto_enumTypes,
		MessageInfos:      file_listener_pkg_schemahandler_proto_schemahandler_proto_msgTypes,
	}.Build()
	File_listener_pkg_schemahandler_proto_schemahandler_proto = out.File
	file_listener_pkg_schemahandler_proto_schemahandler_proto_goTypes = nil
	file_listener_pkg_schemahandler_proto_schemahandler_proto_depIdxs = nil
}
