// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: listener/pkg/schemahandler/proto/schemahandler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchemaHandler_Subscribe_FullMethodName = "/proto.SchemaHandler/Subscribe"
)

// SchemaHandlerClient is the client API for SchemaHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchemaHandlerClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
}

type schemaHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaHandlerClient(cc grpc.ClientConnInterface) SchemaHandlerClient {
	return &schemaHandlerClient{cc}
}

func (c *schemaHandlerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchemaHandler_ServiceDesc.Streams[0], SchemaHandler_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaHandler_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

// SchemaHandlerServer is the server API for SchemaHandler service.
// All implementations must embed UnimplementedSchemaHandlerServer
// for forward compatibility.
type SchemaHandlerServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	mustEmbedUnimplementedSchemaHandlerServer()
}

// UnimplementedSchemaHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemaHandlerServer struct{}

func (UnimplementedSchemaHandlerServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSchemaHandlerServer) mustEmbedUnimplementedSchemaHandlerServer() {}
func (UnimplementedSchemaHandlerServer) testEmbeddedByValue()                       {}

// UnsafeSchemaHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaHandlerServer will
// result in compilation errors.
type UnsafeSchemaHandlerServer interface {
	mustEmbedUnimplementedSchemaHandlerServer()
}

func RegisterSchemaHandlerServer(s grpc.ServiceRegistrar, srv SchemaHandlerServer) {
	// If the following call panics, it indicates UnimplementedSchemaHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchemaHandler_ServiceDesc, srv)
}

func _SchemaHandler_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchemaHandlerServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchemaHandler_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

// SchemaHandler_ServiceDesc is the grpc.ServiceDesc for SchemaHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SchemaHandler",
	HandlerType: (*SchemaHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SchemaHandler_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "listener/pkg/schemahandler/proto/schemahandler.proto",
}
